security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
  providers:
    my_new_provider:
      id: blogsh.test.my_custom_user_provider
  firewalls:
    main:
      pattern: ^/
      http_basic:
        provider: my_new_provider